name: CI Releases

on:
  push:
    tags:
      - '*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ci_builds.yml
        workflow_conclusion: success
        commit: ${{github.event.pull_request.head.sha}}
        path: ./artifacts/
        event: push
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: zip
        GHR_PATH: ./artifacts/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}